version: 2
jobs:
  test:    
    docker:
      - image: circleci/node:latest
    steps:
      - setup_remote_docker
      - checkout      
      - run: ./run_tests.sh
  build:
    docker:
      - image: google/cloud-sdk      
    steps:
      - setup_remote_docker:
          docker_layer_caching: true
      - checkout
      - run:       
          name: Store Service Account
          command: echo $ACCT_AUTH > ${HOME}/gcloud-service-key.json
      - run:
          name: "Build and push the image"
          command: |
                # if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin                  
                  git config --global user.email "ci@gochain.io"
                  git config --global user.name "CI"
                  git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
                  ./release.sh
                # fi
workflows:
  version: 2  
  test-and-release:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master