version: 2
jobs:
  test:
    machine: true        
    steps:
      - checkout
      - run:
          name: update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: make test
  build:
    docker:
      - image: google/cloud-sdk      
    steps:
      - run:
          name: "Build and push the image"
          command: |
                if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                  echo $ACCT_AUTH > ${HOME}/gcloud-service-key.json              
                  git config --global user.email "ci@gochain.io"
                  git config --global user.name "CI"
                  git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
                  make release
                fi
workflows:
  version: 2
  prepare-accept-deploy:
    jobs:
      - test      
      - release-master:
          filters:
            branches:
              only: master
          requires:
            - test
            - build