version: 2
jobs:
  test:
    machine: true        
    steps:
      - checkout
      - run:
          name: update Docker
          command: |
            docker version
            sudo service docker stop
            curl -fsSL https://get.docker.com/ | sudo sh
      - run: docker version
      - run: make test
  build:
    docker:
      - image: google/cloud-sdk      
    steps:
      - checkout
      - run:       
          name: Store Service Account
          command: echo $ACCT_AUTH > ${HOME}/gcloud-service-key.json
      - run:
          name: "Build and push the image"
          command: |
                # if [[ "${CIRCLE_BRANCH}" == "master" && -z "${CIRCLE_PR_REPONAME}" ]]; then
                  echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin                  
                  git config --global user.email "ci@gochain.io"
                  git config --global user.name "CI"
                  git branch --set-upstream-to=origin/${CIRCLE_BRANCH} ${CIRCLE_BRANCH}
                  make release
                # fi
workflows:
  version: 2
  test:
    jobs:
      - test
  test-and-release:
    jobs:
      - test
      - build:
          requires:
            - test
        # filters:
        #   branches:
        #     only: master